# Generated by Django 6.0.7 on 2026-08-14 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='Support Engineer', max_length=100)),
                ('skills', models.JSONField(default=list, help_text="List of skills e.g. ['Django', 'Python', 'REST API']")),
                ('status', models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline'), ('BUSY', 'Busy')], default='ONLINE', max_length=20)),
                ('workload', models.IntegerField(default=50, help_text='Workload percentage 0-100%')),
                ('total_assigned', models.IntegerField(default=0)),
                ('total_resolved', models.IntegerField(default=0)),
                ('average_response_time', models.CharField(default='12 mins', max_length=50)),
                ('average_resolution_time', models.CharField(default='1.8 hours', max_length=50)),
                ('customer_rating', models.FloatField(default=4.8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
